rover:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Effort Controllers ---------------------------------------
  wheel_fr_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_fr_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  wheel_fl_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_fl_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  wheel_rr_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_rr_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}

  wheel_rl_effort_controller:
    type: effort_controllers/JointEffortController
    joint: wheel_rl_joint
    pid: {p: 100.0, i: 0.1, d: 10.0}
  
  gazebo_ros_control:
    pid_gains:
      wheel_fr_joint: {p: 1.0, i: 3.0, d: 0.0, i_clamp: 2.0}
      wheel_fl_joint: {p: 1.0, i: 3.0, d: 0.0, i_clamp: 2.0}
      wheel_rr_joint: {p: 1.0, i: 3.0, d: 0.0, i_clamp: 2.0}
      wheel_rl_joint: {p: 1.0, i: 3.0, d: 0.0, i_clamp: 2.0}